name: macOS

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]
  workflow_dispatch:

jobs:
  macos:
    name: ${{ matrix.config.name }}
    runs-on: ${{ matrix.config.os }}
    
    strategy:
      fail-fast: false
      matrix:
        config:
          - {
              name: "macOS 12 Release",
              os: macos-12,
              cc: "clang",
              cxx: "clang++",
              build_type: "Release"
            }
          - {
              name: "macOS 12 Debug", 
              os: macos-12,
              cc: "clang",
              cxx: "clang++",
              build_type: "Debug"
            }
          - {
              name: "macOS 13 Release",
              os: macos-13,
              cc: "clang",
              cxx: "clang++",
              build_type: "Release"
            }
          - {
              name: "macOS 13 Debug", 
              os: macos-13,
              cc: "clang",
              cxx: "clang++",
              build_type: "Debug"
            }
          - {
              name: "macOS Latest",
              os: macos-latest,
              cc: "clang",
              cxx: "clang++",
              build_type: "Release"
            }

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Dependencies  
        run: |
          brew install ninja

      - name: Setup CMake
        uses: jwlawson/actions-setup-cmake@v1.14
        with:
          cmake-version: '3.25'

      - name: Set Environment Variables
        run: |
          echo "CC=${{ matrix.config.cc }}" >> $GITHUB_ENV
          echo "CXX=${{ matrix.config.cxx }}" >> $GITHUB_ENV

      - name: Configure CMake
        run: |
          cmake -B build \
            -DCMAKE_BUILD_TYPE=${{ matrix.config.build_type }} \
            -G Ninja

      - name: Build
        run: cmake --build build --config ${{ matrix.config.build_type }} --parallel

      - name: Test
        working-directory: build
        run: ctest --output-on-failure --parallel -C ${{ matrix.config.build_type }}

      - name: Run Tests Directly
        working-directory: build
        run: ./circular_buffer_tests --gtest_output=xml:test_results.xml

      - name: Run Performance Tests
        working-directory: build
        run: ./performance_test > performance_results.txt

      - name: Upload Test Results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: test-results-${{ matrix.config.name }}
          path: build/test_results.xml

      - name: Upload Performance Results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: performance-results-${{ matrix.config.name }}
          path: build/performance_results.txt 