name: Windows

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]
  workflow_dispatch:

jobs:
  windows:
    name: ${{ matrix.config.name }}
    runs-on: ${{ matrix.config.os }}
    
    strategy:
      fail-fast: false
      matrix:
        config:
          - {
              name: "Windows MSVC 2022 Release",
              os: windows-2022,
              build_type: "Release",
              cc: "cl",
              cxx: "cl",
              environment_script: "C:/Program Files/Microsoft Visual Studio/2022/Enterprise/VC/Auxiliary/Build/vcvars64.bat"
            }
          - {
              name: "Windows MSVC 2022 Debug", 
              os: windows-2022,
              build_type: "Debug",
              cc: "cl",
              cxx: "cl",
              environment_script: "C:/Program Files/Microsoft Visual Studio/2022/Enterprise/VC/Auxiliary/Build/vcvars64.bat"
            }
          - {
              name: "Windows MSVC 2019 Release",
              os: windows-2019,
              build_type: "Release",
              cc: "cl",
              cxx: "cl",
              environment_script: "C:/Program Files (x86)/Microsoft Visual Studio/2019/Enterprise/VC/Auxiliary/Build/vcvars64.bat"
            }

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup CMake
        uses: jwlawson/actions-setup-cmake@v1.14
        with:
          cmake-version: '3.25'

      - name: Setup MSVC
        uses: microsoft/setup-msbuild@v1.3

      - name: Configure CMake
        run: |
          cmake -B build -G "Visual Studio 17 2022" -A x64 -DCMAKE_BUILD_TYPE=${{ matrix.config.build_type }}

      - name: Build
        run: cmake --build build --config ${{ matrix.config.build_type }} --parallel

      - name: Test
        working-directory: build
        run: ctest --output-on-failure --parallel -C ${{ matrix.config.build_type }}

      - name: Run Tests Directly
        working-directory: build
        run: .\${{ matrix.config.build_type }}\circular_buffer_tests.exe --gtest_output=xml:test_results.xml

      - name: Run Performance Tests
        working-directory: build
        run: .\${{ matrix.config.build_type }}\performance_test.exe

      - name: Upload Test Results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: test-results-${{ matrix.config.name }}
          path: build/test_results.xml

      - name: Upload Performance Results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: performance-results-${{ matrix.config.name }}
          path: build/performance_*.txt 